services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2
    container_name: pocket-id
    restart: unless-stopped
    env_file: .env
    networks:
      - traefik-public
    volumes:
      - "pocket-id:/app/data"
      - /root/.ssh/id_rsa:/app/data/id_rsa
    labels:
      - traefik.enable=true
      - traefik.http.routers.pocket-id.rule=Host(`id.oxcafebabe.cn`)
      - traefik.http.routers.pocket-id.entrypoints=websecure
      - traefik.http.services.pocket-id.loadbalancer.server.port=1411
      - traefik.http.routers.pocket-id.service=pocket-id
      - traefik.http.routers.pocket-id.tls.certresolver=leresolver

volumes:
  pocket-id: 
networks:
  traefik-public:
    external: true
